/*
 * \file configHaveHeader.h
 * This file is part of Enblend
 * Licence details can be found in the file COPYING.
 *
 * This is the compilation configuration file for enblend.
 * It was generated by cmake.
 * You might want to change some of the defaults if something goes wrong
 * during the compilation.
 */

#ifndef _CONFIG_HEADER_H
#define _CONFIG_HEADER_H

${listHaveHeaders}

#endif /* _CONFIG_HEADER_H */

