.TH enblend 1 "December 11, 2005" "" ""
.SH NAME
enblend \- combine images using a multiresolution spline
.SH SYNOPSIS
.B enblend [OPTIONS] -o output-file input-files...
.SH DESCRIPTION
Enblend
overlays multiple TIFF images using the Burt & Adelson multiresolution spline.
This technique tries to make the seams between the input images invisible.
The basic idea is that image features should be blended across a transition
zone proportional in size to the spatial frequency of the features. For example,
objects like trees and windowpanes have rapid changes in color. By blending
these features in a narrow zone, you will not be able to see the seam because
the eye already expects to see color changes at the edge of these features.
Clouds and sky are the opposite. These features have to be blended across a
wide transition zone because any sudden change in color will be immediately
noticeable.

Enblend expects each input TIFF to have an alpha channel. The alpha channel
should indicate the region of the file that has valid image data. Enblend
compares the alpha regions in the input files to find the areas where images
overlap. Alpha channels can be used to indicate to Enblend that certain
portions of an input image should not contribute to the final image.

Enblend does
.B not
align images for you. Use a tool like
.B Hugin
or
.B PanoTools
to do this. The TIFFs produced by these programs are exactly what
enblend is designed to work with.
Sometimes these GUIs allow you to select feathering for the edges of
your images. This treatment is detrimental to Enblend. Turn off
feathering by deselecting it or setting the feather width to zero.

Enblend blends the images in the order you specify on the command line.
You should order your images according to the way that they overlap,
for example from left-to-right across the panorama.
If you are making a multi-row panorama, I recommend blending each horizontal
row individually, and then running Enblend a final time to blend all of the
rows together vertically.

.SH COMMON OPTIONS
.IP -a
Pre-assemble non-overlapping images before each blending iteration.
This overrides the default behavior which is to blend the images sequentially
in the order given on the command line.
Enblend will do fewer blending iterations, but it will do more work in each
iteration.
.IP -h
Print information on the available options.
.IP "-l num"
Use exactly this many levels for pyramid blending. This trades off quality
of results for faster execution time and lower memory usage. The default is
to use as many levels as possible given the size of the overlap region.
Enblend may still use a smaller number of levels if the geometry of the images
demands it.
.IP "-o output-file"
Required. Specify the name of the output file.
.IP -v
Verbose output.
.IP -w
Blend around the -180/+180 boundary. Useful for full-360 panoramas.
Enblend currently does not blend the zenith or the nadir, so you may still see
some seams in these areas.
.IP -z
Use LZW compression for the output images.
.IP input-files
Two or more TIFF files.

.SH EXTENDED OPTIONS
.IP "-b kilobytes"
Set the block size for Enblend's image cache. This is the amount of data that
Enblend will move to and from the disk in one go. The default is 2 MiB which
should be good for most systems.
.IP -c
Use the CIE L*a*b* color space for blending.
.IP -g
Gimp (ver. < 2) and Cinepaint exhibit unusual behaviors when loading
images with unassociated alpha channels. Use the -g flag to work
around this. With this flag Enblend will create the output image with
the associated alpha tag set, even though the image is really
unassociated alpha.
.IP "-m megabytes"
Set the size of Enblend's image cache. This is the amount of memory Enblend
will use for storing image data before swapping to disk.
The default is 1 GiB.

.SH ADDITIONAL INFORMATION
Please see the Enblend web page at:
.PP
http://www-cad.eecs.berkeley.edu/~mihal/enblend/

.SH AUTHOR
Andrew Mihal <mihal@eecs.berkeley.edu>
